---
# Too picky.
LineLength:
  Enabled: false

# This should truly be on for well documented gems.
Documentation:
  Enabled: false

# Neatly aligned code is too swell.
SingleSpaceBeforeFirstArg:
  Enabled: false

# Don't mess with RSpec DSL.
Blocks:
  Exclude:
    - 'spec/**/*'

# Skip this.
StringLiterals:
  Enabled: false

SignalException:
  Enabled: false
